apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kvue-vault-web-app"
  title: "Kvue Vault Web App"
  description: "Kvue Vault Web App"
  annotations:
    backstage.io/techdocs-ref: dir:.
    bitbucket/repo-slug: kenvue
    bitbucket/repo-key: "kvue-vault-web-app"
    jenkins.io/job-full-name: KAKM/
    backstage.io/linguist: https://bitbucket.org/kenvue/kvue-vault-web-app
  tags:
    - "react"
spec:
  type: website
  owner: "group:default/data-archival-team"
  lifecycle: "Experimental"
